
version: '3'
services:
  ${SERVICE_NAME1}:
    container_name: ${CONTAINER_NAME1}
    image: ${IMAGE_NAME1}:${IMAGE_TAG1}
    # build:
    #   context: ${APP_LOCATION1}
    #   dockerfile: ${DOCKERFILE_NAME1}
    ports:
      - "3000:3000"
      